#!/usr/bin/env python3
"""
Convert a flat binary x86_64 ELF to a C byte array.
This is used to embed user programs into the kernel's ramfs.
"""
import sys
import os

def create_simple_elf_binary():
    """Create a minimal x86_64 ELF executable that prints a message and exits."""
    
    # ELF64 header (64 bytes)
    e_ident = bytearray(16)
    e_ident[0:4] = b'\x7fELF'      # Magic
    e_ident[4] = 2                   # ELFCLASS64
    e_ident[5] = 1                    # ELFDATA2LSB (little endian)
    e_ident[6] = 1                    # EV_CURRENT
    e_ident[7] = 0                    # ELF_OSABI_NONE
    
    ehdr = bytearray(64)
    ehdr[0:16] = e_ident
    ehdr[16:18] = (2).to_bytes(2, 'little')       # ET_EXEC
    ehdr[18:20] = (62).to_bytes(2, 'little')      # EM_X86_64
    ehdr[24:28] = (1).to_bytes(4, 'little')       # e_version
    ehdr[32:40] = (0x400080).to_bytes(8, 'little') # e_entry
    ehdr[40:48] = (64).to_bytes(8, 'little')      # e_phoff
    ehdr[56:60] = (0).to_bytes(4, 'little')       # e_flags
    ehdr[60:62] = (64).to_bytes(2, 'little')      # e_ehsize
    ehdr[54:56] = (56).to_bytes(2, 'little')      # e_phentsize
    
    # Program header (56 bytes)
    phdr = bytearray(56)
    phdr[0:4] = (1).to_bytes(4, 'little')         # PT_LOAD
    phdr[4:8] = (5).to_bytes(4, 'little')         # PF_R | PF_X
    phdr[8:16] = (0).to_bytes(8, 'little')        # p_offset
    phdr[16:24] = (0x400080).to_bytes(8, 'little') # p_vaddr
    phdr[24:32] = (0x400080).to_bytes(8, 'little') # p_paddr
    phdr[32:40] = (0x1000).to_bytes(8, 'little')   # p_filesz
    phdr[40:48] = (0x1000).to_bytes(8, 'little')   # p_memsz
    phdr[48:56] = (0x1000).to_bytes(8, 'little')   # p_align
    
    # Code: 64-bit x86_64 syscall
    # message: "User test: Hello from user mode!\n"
    code = bytearray([
        # syscall write(1, msg, 32)
        0x48, 0xc7, 0xc0, 0x02, 0x00, 0x00, 0x00, # mov rax, 2 (SYS_WRITE)
        0x48, 0xc7, 0xc7, 0x01, 0x00, 0x00, 0x00, # mov rdi, 1 (stdout)
        0x48, 0x8d, 0x35, 0x20, 0x00, 0x00, 0x00, # lea rsi, [rel msg]
        0x48, 0xc7, 0xc2, 0x20, 0x00, 0x00, 0x00, # mov rdx, 32
        0x0f, 0x05,                               # syscall
        
        # syscall getpid()
        0x48, 0xc7, 0xc0, 0x09, 0x00, 0x00, 0x00, # mov rax, 9 (SYS_GETPID)
        0x0f, 0x05,                               # syscall
        # rax now contains pid
        
        # syscall exit(0)
        0x48, 0xc7, 0xc0, 0x05, 0x00, 0x00, 0x00, # mov rax, 5 (SYS_EXIT)
        0x48, 0xc7, 0xc7, 0x00, 0x00, 0x00, 0x00, # mov rdi, 0 (exit code)
        0x0f, 0x05,                               # syscall
        
        # padding to reach page boundary
        0x90, 0x90, 0x90, 0x90, 0x90, 0x90,
    ])
    
    # Message (32 bytes, aligned)
    msg = b"User test: Hello from user mode!\n"
    
    # Align to page size
    while len(code) % 16 != 0:
        code.append(0x90)  # NOP padding
    
    # Assemble the binary
    binary = ehdr + phdr + code + msg
    
    return binary

def elf_to_c_array(name, binary):
    """Convert binary data to a C byte array."""
    c_code = f"// Auto-generated by elf_to_c.py\n"
    c_code += f"// {name} - embedded ELF binary\n\n"
    c_code += f"static const uint8_t {name}_elf[] = {{\n"
    
    for i in range(0, len(binary), 16):
        chunk = binary[i:i+16]
        hex_values = ', '.join(f'0x{b:02X}' for b in chunk)
        c_code += f"    {hex_values},\n"
    
    c_code += "};\n"
    c_code += f"static const uint64_t {name}_elf_size = {len(binary)};\n"
    
    return c_code

if __name__ == '__main__':
    binary = create_simple_elf_binary()
    
    output = elf_to_c_array('test_user', binary)
    
    print(f"Generated ELF binary: {len(binary)} bytes")
    print(f"\n{output}")
